spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/minitube
spring.datasource.username=minitube_app
spring.datasource.password=DBpassword33#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true